# Generated by Django 5.2.7 on 2025-12-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tlannouncement',
            name='show_in_calendar',
            field=models.BooleanField(default=True),
        ),
    ]
