# Generated by Django 5.2.7 on 2026-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('management', 'Management'), ('delivery_manager', 'Delivery Manager'), ('project_manager', 'Project Manager'), ('hr', 'HR'), ('tl', 'Team Leader'), ('employee', 'Employee'), ('intern', 'Intern')], default='employee', max_length=20),
        ),
    ]
