# Generated by Django 5.2.7 on 2025-12-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(max_length=6),
        ),
    ]
