# Generated by Django 5.2.7 on 2025-12-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('department', models.CharField(choices=[('HR', 'Human Resources'), ('EMP', 'Employee'), ('TL', 'Team Lead'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('IT', 'IT Department')], max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('show_in_calendar', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('working_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('finalized', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('hra_percent', models.DecimalField(decimal_places=2, default=22.5, max_digits=5)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='TLAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show_in_calendar', models.BooleanField(default=True)),
            ],
        ),
    ]
