# Generated by Django 5.2.7 on 2026-01-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='audience',
        ),
    ]
