# Generated by Django 5.2.7 on 2025-12-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='show_in_calendar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tlannouncement',
            name='show_in_calendar',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tlannouncement',
            name='date',
            field=models.DateField(),
        ),
    ]
