# Generated by Django 5.2.7 on 2026-02-20 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payslip',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='payslip',
            name='profile',
        ),
        migrations.DeleteModel(
            name='SalaryStructure',
        ),
        migrations.DeleteModel(
            name='Payslip',
        ),
    ]
