# Generated by Django 5.2.7 on 2025-12-18 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_employeeprofile_date_of_joining_and_more'),
        ('hr', '0003_announcement_show_in_calendar_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('hra_percent', models.DecimalField(decimal_places=2, default=22.5, max_digits=5)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('working_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('finalized', models.BooleanField(default=False)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_generated_payslips', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_payslips', to='emp.employeeprofile')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('profile', 'year', 'month')},
            },
        ),
    ]
