# Generated by Django 5.2.7 on 2026-02-05 05:48

import datetime
import django.core.validators
import emp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('duration_time', models.DurationField(blank=True, max_length=20, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('working', 'Working'), ('present', 'Present'), ('halfday', 'Half Day'), ('absent', 'Absent')], default='working', max_length=20)),
                ('late_arrivals', models.BooleanField(default=False)),
                ('total_hours', models.DurationField(default=datetime.timedelta(0))),
                ('overtime', models.DurationField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('announcement', 'Announcement'), ('holiday', 'Holiday')], default='announcement', max_length=50)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible_to_tl_hr', models.BooleanField(default=True)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeIDSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(editable=False, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='emp_id must be in format WZG-AI-0000', regex='^WZG-AI-\\d{4}$')])),
                ('work_email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80, null=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhaar_front_image', models.ImageField(blank=True, null=True, upload_to='ids/aadhaar/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('aadhaar_back_image', models.ImageField(blank=True, null=True, upload_to='ids/aadhaar/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('pan', models.CharField(blank=True, max_length=20, null=True)),
                ('pan_front_image', models.ImageField(blank=True, null=True, upload_to='ids/pan/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('pan_back_image', models.ImageField(blank=True, null=True, upload_to='ids/pan/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_front_image', models.ImageField(blank=True, null=True, upload_to='ids/passport/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('passport_back_image', models.ImageField(blank=True, null=True, upload_to='ids/passport/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('id_card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('id_card_front_image', models.ImageField(blank=True, null=True, upload_to='ids/idcard/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('id_card_back_image', models.ImageField(blank=True, null=True, upload_to='ids/idcard/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('job_title', models.CharField(blank=True, max_length=150, null=True)),
                ('department', models.CharField(blank=True, choices=[('Python', 'Python'), ('QA', 'QA'), ('Java', 'Java'), ('UI/UX', 'UI/UX'), ('React', 'React'), ('Cyber Security', 'Cyber Security'), ('Digital Marketing', 'Digital Marketing'), ('HR', 'HR'), ('BDM', 'BDM'), ('Networking', 'Networking'), ('Cloud', 'Cloud (AWS / DevOps)')], max_length=100, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('id_image', models.ImageField(blank=True, null=True, upload_to='employee/id_cards/', validators=[emp.validators.validate_file_size, emp.validators.validate_image_extension])),
                ('bank_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, max_length=64, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('branch', models.CharField(blank=True, max_length=150, null=True)),
                ('role', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave'), ('UNPAID', 'Unpaid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave')], max_length=20)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('used', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave'), ('UNPAID', 'Unpaid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reason', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('tl_approved', 'TL Approved'), ('tl_rejected', 'TL Rejected'), ('hr_approved', 'HR Approved'), ('hr_rejected', 'HR Rejected'), ('pending_hr', 'Pending HR'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='applied', max_length=30)),
                ('tl_remarks', models.TextField(blank=True, null=True)),
                ('hr_remarks', models.TextField(blank=True, null=True)),
                ('last_action_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('notif_type', models.CharField(choices=[('announcement', 'Announcement'), ('meeting', 'Meeting'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('policy', 'Policy')], default='announcement', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extra', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('working_days', models.PositiveIntegerField(default=0)),
                ('days_present', models.PositiveIntegerField(default=0)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('details', models.JSONField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('finalized', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('policy_type', models.CharField(choices=[('policy', 'Company Policy'), ('terms', 'Terms & Conditions'), ('resignation', 'Resignation Rules'), ('separation', 'Separation Rules')], default='policy', max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('monthly_ctc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('basic_percent', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('hra_percent', models.DecimalField(decimal_places=2, default=45.0, max_digits=5)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('grace_minutes', models.PositiveIntegerField(default=5)),
                ('late_threshold', models.PositiveIntegerField(default=15)),
            ],
        ),
        migrations.CreateModel(
            name='TimesheetDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('is_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(blank=True, max_length=20)),
                ('task', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('manual', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
