# Generated by Django 5.2.7 on 2026-01-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_initial'),
        ('projects', '0002_projectaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetentry',
            name='project_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_entries', to='projects.task'),
        ),
    ]
