# Generated by Django 5.2.7 on 2025-12-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('tl_approved', 'TL Approved'), ('tl_rejected', 'TL Rejected'), ('hr_approved', 'HR Approved'), ('hr_rejected', 'HR Rejected'), ('pending_hr', 'Pending HR'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='applied', max_length=30),
        ),
    ]
