# Generated by Django 5.2.7 on 2025-12-13 07:47

from django.db import migrations

def seed_leave_types(apps, schema_editor):
    LeaveType = apps.get_model("emp", "LeaveType")

    leave_types = [
        "Casual Leave",
        "Sick Leave",
        "Earned Leave",
        "Maternity Leave",
        "Paternity Leave",
    ]

    for name in leave_types:
        LeaveType.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(seed_leave_types),
    ]
