# Generated by Django 5.2.7 on 2025-12-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_remote',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late_by_seconds',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='manual_entry',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='note',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='overtime_seconds',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='file',
        ),
        migrations.AddField(
            model_name='attendance',
            name='duration_time',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('present', 'Present'), ('halfday', 'Half Day'), ('absent', 'Absent')], default='working', max_length=20),
        ),
    ]
