# Generated by Django 5.2.7 on 2026-02-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(blank=True, choices=[('Python', 'Python'), ('QA', 'QA'), ('Java', 'Java'), ('UI/UX', 'UI/UX'), ('React', 'React'), ('Cyber Security', 'Cyber Security'), ('Digital Marketing', 'Digital Marketing'), ('HR', 'HR'), ('BDM', 'BDM'), ('Networking', 'Networking'), ('Cloud', 'Cloud')], max_length=100, null=True),
        ),
    ]
