# Generated by Django 5.2.7 on 2025-12-18 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetday',
            name='attendance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timesheet_day', to='emp.attendance'),
        ),
        migrations.AddField(
            model_name='timesheetday',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timesheetday',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_timesheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheetday',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, null=True),
        ),
    ]
