# Generated by Django 5.2.7 on 2025-12-09 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_leaverequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day', models.CharField(blank=True, max_length=20)),
                ('task', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField(
                    blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manual', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='timesheet_entries', to='emp.employeeprofile')),
            ],
            options={
                'ordering': ['-date', '-start_time'],
                'unique_together': {('profile', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
