# Generated by Django 5.2.7 on 2026-03-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_alter_employeeprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual_Leave'), ('SICK', 'Sick_Leave'), ('PAID', 'Paid_Leave'), ('UNPAID', 'Unpaid_Leave'), ('MATERNITY', 'Maternity_Leave'), ('PATERNITY', 'Paternity_Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual_Leave'), ('SICK', 'Sick_Leave'), ('PAID', 'Paid_Leave'), ('UNPAID', 'Unpaid_Leave'), ('MATERNITY', 'Maternity_Leave'), ('PATERNITY', 'Paternity_Leave')], max_length=20),
        ),
    ]
