# Generated by Django 5.2.7 on 2025-12-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_seed_leave_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='reminder_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
