# Generated by Django 5.2.7 on 2026-03-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_leavebalance_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='exit_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
