# Generated by Django 5.2.7 on 2025-12-27 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_alter_leavebalance_leave_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='last_reminder_at',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='reminder_count',
        ),
        migrations.AddField(
            model_name='attendance',
            name='late_arrivals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='total_hours',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='duration_time',
            field=models.DurationField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave'), ('UNPAID', 'Unpaid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave'), ('UNPAID', 'Unpaid Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('meeting', 'Meeting'), ('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('leave', 'Leave'), ('payroll', 'Payroll'), ('policy', 'Policy')], default='announcement', max_length=50),
        ),
    ]
