# Generated by Django 5.2.7 on 2025-12-18 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0004_attendance_last_reminder_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='days_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_generated_payslips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_payslips', to='emp.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='payslip',
            name='working_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='hra_percent',
            field=models.DecimalField(decimal_places=2, default=45.0, max_digits=5),
        ),
    ]
