# Generated by Django 5.2.7 on 2026-04-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_employeeprofile_exit_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
