# Generated by Django 5.2.7 on 2025-12-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0005_alter_timesheetentry_options_timesheetday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='duration_seconds',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
