# Generated by Django 5.2.7 on 2026-01-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginsupportticket',
            name='issue_type',
            field=models.CharField(choices=[('OTP', 'OTP not received'), ('PASSWORD', 'Forgot password'), ('LOCKED', 'Account locked'), ('LOGIN', 'Unable to login'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
